[tool.poetry]
name = "minager"
version = "0.0.1"
description = "Minager - mind management tool"
authors = ["Sultan Nasyrov <tightbtctrader@gmail.com>"]
readme = "README.md"

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.poetry.scripts]
migrate = "scripts.migrate:run"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.12"}
pydantic = "^2.11.5"
aiohttp = {extras = ["speedups"], version = "^3.9.3"}
pyjwt = "^2.8.0"
pydantic-settings = "^2.9.1"
aio-pika = "^9.4.3"
yarl = "^1.13.1"
requests = "^2.32.3"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.41"}
sqlmodel = "^0.0.24"
alembic = "^1.16.1"
motor = "^3.7.1"
asyncpg = "^0.30.0"
surrealdb = "^1.0.4"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
fastapi-users = {extras = ["sqlalchemy"], version = "^15.0.1"}

[tool.poetry.group.dev.dependencies]
ipython = "^8.18.1"
pre-commit = "^3.8.0"
psycopg = "^3.2.9"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.23.2"
httpx = "^0.26.0"
pytest-mock = "^3.14.0"
faker = "^35.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
